repositoryUrlJS: https://github.com/dynamsoft-docs/barcode-reader-docs-js/blob/main
repository: dynamsoft-docs/barcode-reader-docs-js
docFullPath: https://www.dynamsoft.com/barcode-reader/docs/web/
firstLevelUrl: /barcode-reader/docs/web
docRootName: "Barcode Reader JS Edition"
docHomePage: /barcode-reader/docs/web/programming/javascript/

useVersionTree: true

features: /barcode-reader/docs/core/programming/features/
usecases: /barcode-reader/docs/core/programming/usecases/
introduction: /barcode-reader/docs/core/introduction/
programming: /barcode-reader/docs/core/programming/
parameters: /barcode-reader/docs/core/parameters/
parameters_reference: /barcode-reader/docs/core/parameters/reference/
license_activation: /barcode-reader/docs/core/license-activation/
release_notes: /barcode-reader/docs/core/release-notes/
performance: /barcode-reader/docs/core/performance/
understanding: /barcode-reader/docs/core/understanding/
faq: /barcode-reader/docs/core/faq/
faq_js: /barcode-reader/docs/web/programming/javascript/faq/

js: /barcode-reader/docs/web/programming/javascript/
js_api: /barcode-reader/docs/web/programming/javascript/api-reference/
dce_js_api: /camera-enhancer/docs/web/programming/javascript/api-reference/
dcp_js_api: /code-parser/docs/web/programming/javascript/api-reference/
js_release_notes: /barcode-reader/docs/web/programming/javascript/release-notes/
image_parameters: /barcode-reader/docs/core/parameters/reference/image-parameter/
scenario_settings: /barcode-reader/docs/core/parameters/scenario-settings/
enumerations: /barcode-reader/docs/core/parameters/enum/
code_types: /code-parser/docs/core/code-types/

architecture: /capture-vision/docs-archive/core/architecture/
enums: /capture-vision/docs-archive/core/enums/
parameter: /capture-vision/docs-archive/core/parameters/
dcv_parameters: /capture-vision/docs-archive/core/parameters/reference/
dcv_js_api: /capture-vision/docs-archive/web/programming/javascript/api-reference/
dcv_enumerations: /capture-vision/docs-archive/core/enums/
dcv_introduction: /capture-vision/docs-archive/core/introduction/

dcvb_architecture: /capture-vision/docs/core/architecture/
dcvb_enums: /capture-vision/docs/core/enums/
dcvb_parameter: /capture-vision/docs/core/parameters/
dcvb_parameters: /capture-vision/docs/core/parameters/reference/
dcvb_js_api: /capture-vision/docs/web/programming/javascript/api-reference/
dcvb_enumerations: /capture-vision/docs/core/enums/
dcvb_introduction: /capture-vision/docs/core/introduction/

assets: /barcode-reader/docs/web/assets/
edit_icon: /barcode-reader/docs/web/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader/docs/web/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader/docs/web/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader/docs/web/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader/docs/web/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader/docs/web/assets/img-icon/icon-dnt.svg

baseurl: "/barcode-reader/docs/web"
plugins:
  - jemoji

edition: js

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "mobile/programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming-old/javascript"
    values:
      category: "js-repo"
      edition: "js"
      docRootName: "Barcode Reader JavaScript Edition" 
      docHomePage: "/barcode-reader/docs/web/programming/javascript/"
  - scope:
      path: "mobile/programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "server/programming/c"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/c-cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/dotnet"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/python"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/java"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root
