  # This is a basic workflow to help you get started with Actions

name: CI DBR-JS

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: 
    - main 
    #- preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-production.yml@main
    with:
      doc-repo: barcode-reader-docs-js
      doc-url: barcode-reader/docs/web
    secrets: inherit

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-testing.yml@preview
    with:
      doc-repo: barcode-reader-docs-js
      doc-url: barcode-reader/docs/web
    secrets: inherit

  Build-v10:
    if: ${{ github.ref == 'refs/heads/v10' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-testing.yml@DCV-v2
    with:
      doc-repo: barcode-reader-docs-js
      doc-url: barcode-reader/docs/v10/web
      doc-branch: v10
    secrets: inherit
